Removed status prefix from log message.

diff --git a/bin/b0b b/bin/b0b
--- a/bin/b0b
+++ b/bin/b0b
@@ -2,18 +2,17 @@
 
 . b0b.cfg
 
-echo "[INFO] Checking B0b's fitness."
+echo "Checking B0b's health."
 vars=( "$B0B_HOME" "$APP_NAME" "$APP_VERSION" )
 names=( "B0B_HOME" "APP_NAME" "APP_VERSION" )
 for (( i = 0 ; i < ${#vars[@]} ; i++ ))
 do
     if [[ -z "${vars[$i]}" ]]; then
-        echo >&2 "[ERROR] ${names[$i]} has not been set"
+        echo >&2 "Error: ${names[$i]} has not been set"
         exit 1
     fi
 done
 
-echo "[INFO] Dispatching B0b to construction site."
 make -f $B0B_HOME/Makefile \
     APP_NAME="$APP_NAME" \
     APP_VERSION="$APP_VERSION" \
